/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Shady Tex (https://sketchfab.com/ShadyTex4u)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mercury-realistic-8k-215f364627054d25ae03bcd72afda714
Title: Mercury Realistic 8K
*/
"use client"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useGSAP } from "@gsap/react"
import gsap from "gsap"

const Mercury = (props) => {
  const group = useRef()
  const { nodes, materials } = useGLTF("/models/mercury.glb")

  useGSAP(() => {
    gsap.to(group.current.rotation, {
      y: "+=6.28319",
      repeat: -1,
      ease: "linear",
      duration: 100,
    })
  })
  return (
    <group {...props} dispose={null} ref={group}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.venus_Material001_0.geometry}
          material={materials["Material.001"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={791.399}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.atmosphere_Material_0.geometry}
          material={materials.Material}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1337.027}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/models/mercury.glb")
export default Mercury
