/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/saturn-749a350ab9f2404aa69567184c61564a
Title: Saturn
*/
"use client"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useGSAP } from "@gsap/react"
import gsap from "gsap"
const Saturn = (props) => {
  const group = useRef()
  const { nodes, materials } = useGLTF("/models/saturn.glb")

  useGSAP(() => {
    gsap.to(group.current.rotation, {
      y: "+=6.28319",
      repeat: -1,
      ease: "linear",
      duration: 40,
    })
  })
  return (
    <group {...props} dispose={null} ref={group}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.ring}
          rotation={[-Math.PI / 2, 0, -0.236]}
          scale={163.361}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials["Material.002"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/models/saturn.glb")

export default Saturn
